Repository baliola/auction-contracts, pull requests merged in 2022-11, with the labels that each got.

#5 reformat and add require statements to forbid creator to buy their nfts
  contracts/FixedPrice.sol
Labels: bug

#7 fixed Bug creator can buy nft fixed price
  contracts/FixedPrice1155.sol
  utils/require-errors/auction-fixed-price.errors.js
Labels: bug

#8 Enhancement provide type binding time helper
  test/helpers/truffle-time.helpers.js
Labels: enhancement

#9 sdd test fixed price
  package-lock.json
  test/fixed-price/fixed-price.test.js
  test/helpers/bindings/fixed-auction-manager-1155.js
  test/helpers/factory.helpers.js
  test/test-1155/open-bids-1155.js
  test/test-721/timed-auction-721.js
  utils/require-errors/auction-fixed-price.errors.js
  utils/utils.js
Labels: documentation, enhancement

#10 Add Test for fixed price auction contract and manager
  README.md
  contracts/Auction1155.sol
  contracts/Auction721.sol
  contracts/AuctionManager1155.sol
  contracts/AuctionManager721.sol
  contracts/FixedPrice1155.sol
  contracts/FixedPrice1155AuctionManager.sol
  contracts/dummy1155.sol
  migrations/1-kepeng.migration.js
  migrations/1_initial_migration.js
  migrations/2-dummy721.migration.js
  migrations/3-dummy1155.migration.js
  migrations/4-fixed-price.migration.js
  package-lock.json
  package.json
  test/fixed-price/fixed-price.test.js
  test/helpers/auction.helpers.js
  test/helpers/bindings/KEPENG.js
  test/helpers/bindings/auction-1155.js
  test/helpers/bindings/auction-721.js
  test/helpers/bindings/auction-fixed-price-1155.js
  test/helpers/bindings/auction-manager-1155.js
  test/helpers/bindings/auction-manager-721.js
  test/helpers/bindings/dummy-1155.js
  test/helpers/bindings/dummy-721.js
  test/helpers/bindings/fixed-auction-manager-1155.js
  test/helpers/factory.helpers.js
  test/helpers/kepeng.helpers.js
  test/helpers/nft1155.helpers.js
  test/helpers/truffle-time-helpers.js
  test/helpers/truffle-time.helpers.js
  test/test-1155/open-bids-1155.js
  test/test-721/timed-auction-721.js
  truffle-config.js
  type-generator.ts
  utils/require-errors/auction-1155.errors.js
  utils/require-errors/auction-fixed-price.errors.js
  utils/require-errors/common/common-auction-manager.errors.js
  utils/require-errors/common/common-auction.errors.js
  utils/utils.js
Labels: documentation, enhancement

#17 add readme, change filename fixed-price-1155
  README.md
  package.json
  test/fixed-price/fixed-price-1155.test.js
Labels: documentation
