Repository baliola/auction-contracts, pull requests merged in 2022-12, with the labels that each got.

#36 index events collectibles
  contracts/Auction1155.sol
  contracts/Auction721.sol
  contracts/FixedPrice1155.sol
Labels: enhancement

#37 index events main
  contracts/Auction1155.sol
  contracts/Auction721.sol
  contracts/FixedPrice1155.sol
Labels: enhancement

#39 add refill test when auction end
  test/fixed-price/fixed-price-1155.test.js
Labels: documentation

#40 add refill test when auction end - main
  test/fixed-price/fixed-price-1155.test.js
Labels: documentation

#45 added assert range function
  utils/utils.js
Labels: documentation, enhancement
